### ISSUE TITLE
macOS libsamplerate.a is x86_64 only

### ISSUE THREAD

**Issue by danomatika** [roymacdonald/ofxSampleRate#1]
The libsamplerate.a build in `libs/libsamplerate/lib/osx` is x86_64 only. This keeps universal or arm64-only builds from completing successfully.

**Comment by roymacdonald** [comment]
Hi dan. I know  but I dont have an arm64 mac to build the lib. could you make a PR with the arm64 or universal lib please?

**Comment by danomatika** [comment]
If you have macOS 10.15 or newer, you can cross-compile for arm64 on your Intel mac by passing in the `-arch` CFLAG. If you pass multiple values in, you can compile a universal lib. For libsamplerate, this would be something like:

~~~
./configure CFLAGS="-arch x86_64 -arch arm64"
make
~~~

The .a will likely be in a hidden directory, `./libs`. You can check the archs with:

~~~
file ./libs/libsamplerate.a
~~~

Update: This is also something good to wrap into a script to clone libsamplerate, build it, then copy the .a and headers into the libs folder.

**Comment by roymacdonald** [comment]
Oh. Interesting. I didn't know about it being possible. I will check it. thanks.

**Comment by danomatika** [comment]
I can confirm this works on my macOS 11 system. You will need the autotools installed for autogen.sh, otherwise use a release tarball which will have configure pre-generated.

~~~
git clone https://github.com/libsndfile/libsamplerate.git
cd libsamplerate
./autogen.sh
./configure --enable-static --disable-sndfile CFLAGS="-arch x86_64 -arch arm64"
make
~~~

The libsamplerate .a and .dylib will be in `src/.libs`. To confirm multi-arch build:
~~~
% file src/.libs/libsamplerate.a
src/.libs/libsamplerate.a: Mach-O universal binary with 2 architectures: [x86_64:current ar archive random librarycurrent ar archive random library] [arm64]
src/.libs/libsamplerate.a (for architecture x86_64):	current ar archive random library
src/.libs/libsamplerate.a (for architecture arm64):	current ar archive random library
~~~

he process could be wrapped up into a script, if you want.

The compiled libsamplerate.a is included:

[libsamplerate.a.zip](https://github.com/roymacdonald/ofxSampleRate/files/10989100/libsamplerate.a.zip)

**Comment by roymacdonald** [comment]
@danomatika awesome! many thanks.
